'use strict';
const $=id=>document.getElementById(id),C=GameConfig,KEY='etherial-idle-v1';let saved;try{saved=JSON.parse(localStorage.getItem(KEY));}catch{}const engine=new IdleEngine(saved),scene=new PixelScene($('scene'),engine);let storageError=false;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(engine.save()));}catch{if(!storageError){storageError=true;toast('El navegador no permite guardar el progreso.');}}}
let toastTimer;function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function modal(label,title,text){$('modal-label').textContent=label;$('modal-title').textContent=title;$('modal-text').textContent=text;$('modal-body').replaceChildren();if(!$('modal').open)$('modal').showModal();}
function portrait(container,id){container.replaceChildren();const c=document.createElement('canvas');c.width=200;c.height=230;c.setAttribute('aria-label',id==='warrior'?'Guerrero pixelado':id==='ranger'?'Arquera pixelada':'Mago pixelado');container.append(c);PixelScene.paintHero(c.getContext('2d'),id,55,55,2.6);}
function sheet(){const h=engine.hero,s=engine.s,c=$('equipment-hero'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(h)PixelScene.paintHero(ctx,h.id,64,64,3.1);$('sheet-name').textContent=h?h.name:'Tu héroe';$('sheet-class').textContent=h?h.className:'Sin héroe';$('gear-symbol').textContent=h?h.symbol:'⚔';$('gear-name').textContent=h?({warrior:'Espada del Alba',ranger:'Arco de fresno',mage:'Bastón arcano'}[h.id]):'Sin equipar';$('gear-level').textContent=h?'Mejora +'+s.weapon+' · +'+s.weapon*4+' ataque de arma':'Compra tu primer héroe';$('armor-name').textContent=h?({warrior:'Armadura de guardián',ranger:'Atuendo del bosque',mage:'Túnica del arcano'}[h.id]):'Sin equipar';$('armor-health').textContent=h?'Vida máxima de clase y nivel: '+engine.maxHp:'—';$('sheet-level').textContent='Nivel '+s.level;$('sheet-xp').textContent=s.xp+' / '+engine.xpTarget+' EXP';$('sheet-attack').textContent=engine.attack;$('sheet-kills').textContent=s.kills;}
function close(){$('modal').close();} $('close-modal').onclick=close;
function demoCredit(){if(engine.demoCredit()){persist();render();toast('Añadiste 5,000 Blez de prueba. Sin valor real.');}}
function creditButton(){const b=document.createElement('button');b.className='secondary';b.style.width='100%';b.style.marginTop='10px';b.textContent='Añadir 5,000 Blez de prueba';b.onclick=()=>{demoCredit();wallet();};return b;}
function chooseHero(id){const h=C.heroes.find(h=>h.id===id);if(!h)return;if(engine.s.owned.includes(id)){engine.acquire(id);persist();render();tab('battle');toast(h.className+' equipado');return;}modal('TIENDA · BLEZ DE PRUEBA',h.name,'Precio: '+format(h.price)+' Blez. Se descontará del saldo de prueba. Saldo actual: '+format(engine.s.coins)+' Blez.');const b=document.createElement('button');b.className='primary';b.textContent='Comprar · '+format(h.price)+' Blez';b.disabled=engine.s.coins<h.price;b.onclick=()=>{if(!engine.buy(id)){toast('Saldo Blez insuficiente.');return;}persist();close();render();tab('battle');toast('Héroe comprado con Blez de prueba. ¡A cazar!');};$('modal-body').append(b);if(engine.s.coins<h.price){const add=creditButton();add.onclick=()=>{demoCredit();chooseHero(id);};$('modal-body').append(add);}}
function welcome(){modal('BIENVENIDO A ETHERIAL','Elige tu primer cazador','El héroe inicial cuesta 5,000 Blez. Añade saldo de prueba y cómpralo para comenzar. Equivalencia propuesta: 10,000 Blez = 1 TON.');C.heroes.forEach(h=>{const b=document.createElement('button');b.className='mini-hero';b.innerHTML='<span>'+h.symbol+'</span><div><b>'+h.name+'</b><small>'+h.className+'</small></div><em>'+format(h.price)+' Blez →</em>';b.onclick=()=>chooseHero(h.id);$('modal-body').append(b);portrait(b.querySelector('span'),h.id);});}
function wallet(){modal('BLEZ → TON · SIMULACIÓN','Tu saldo Blez','Saldo: '+format(engine.s.coins)+' Blez. Equivalencia propuesta: 5,000 Blez = 0.5 TON · 10,000 Blez = 1 TON. Los retiros reales todavía no están activos.');const label=document.createElement('label');label.textContent='Blez a convertir';const input=document.createElement('input');input.type='number';input.min='1';input.step='1';input.value='5000';input.id='withdraw-amount';label.htmlFor=input.id;const out=document.createElement('p');out.setAttribute('aria-live','polite');function quote(){const q=engine.quoteWithdrawal(Number(input.value));out.textContent=q?q.blez.toLocaleString('es-DO')+' Blez = '+q.ton.toLocaleString('es-DO',{maximumFractionDigits:4})+' TON'+(q.covered?' · Saldo suficiente para esta simulación.':' · Saldo insuficiente.'):'Introduce una cantidad entera positiva de Blez.';}input.oninput=quote;$('modal-body').append(label,input,out,creditButton());quote();}
function bestiary(){modal('ARCHIVO DEL CAZADOR','Bestiario de Etherial','Vida de la primera oleada y del jefe. Las oleadas posteriores tienen más vida.');const grid=document.createElement('div');grid.className='bestiary-grid';C.zones.forEach((z,zone)=>{for(const boss of [false,true]){const card=document.createElement('article');card.className='bestiary-card';const c=document.createElement('canvas');c.width=180;c.height=160;c.setAttribute('aria-label',boss?z.boss:z.enemy);c.getContext('2d').imageSmoothingEnabled=false;c.getContext('2d').drawImage(PixelScene.monsterPortrait(zone,boss),0,0,180,160);const label=document.createElement('small');label.textContent=boss?'JEFE · '+z.name:z.name;const name=document.createElement('b');name.textContent=boss?z.boss:z.enemy;const stats=document.createElement('p');stats.textContent='♥ '+Math.round(z.hp*(boss?6.88:1))+' vida · ◆ '+z.reward*(boss?5:1)+' Blez';card.append(c,label,name,stats);grid.append(card);}});$('modal-body').append(grid);}$('bestiary').onclick=bestiary;
$('wallet').onclick=wallet;$('wallet-info').onclick=wallet;
function tab(name){for(const el of document.querySelectorAll('.view'))el.hidden=el.id!==name+'-view';for(const b of document.querySelectorAll('nav button'))b.classList.toggle('active',b.dataset.tab===name);render();}for(const b of document.querySelectorAll('nav button'))b.onclick=()=>tab(b.dataset.tab);$('open-map').onclick=()=>tab('map');
function format(n){return Math.floor(n).toLocaleString('es-DO');}
function render(){const s=engine.s,h=engine.hero;$('coins').textContent=format(s.coins);$('kills').textContent=format(s.kills);$('level').textContent=String(s.level).padStart(2,'0');$('zone-number').textContent='EXPEDICIÓN '+String(s.zone+1).padStart(2,'0');$('zone-name').textContent=engine.zone.name;$('scene').setAttribute('aria-label','Combate automático en '+engine.zone.name);document.querySelector('.arena').classList.toggle('boss-arena',s.wave===10);$('stage').textContent=(s.wave===10?'JEFE':'Oleada '+s.wave)+' / 10';$('status').textContent=!h?'ESPERANDO HÉROE':s.paused?'EN DESCANSO':'CAZANDO EN AUTOMÁTICO';$('enemy-name').textContent=engine.enemyName;$('hero-hp').style.width=engine.maxHp?s.hp/engine.maxHp*100+'%':'0%';$('wave-track').innerHTML=Array.from({length:10},(_,i)=>'<span class="'+(i+1<s.wave?'done':i+1===s.wave?'current':'')+'" '+(i+1===s.wave?'aria-current="step"':'')+' title="'+(i===9?'Jefe':'Oleada '+(i+1))+'">'+(i===9?'♛':i+1)+'</span>').join('');$('enemy-hp').style.width=s.enemyHp/engine.enemyMax*100+'%';$('hero-name').textContent=h?h.name:'Elige tu héroe';if(h)portrait($('portrait'),h.id);else $('portrait').textContent='⚔';$('xp-bar').style.width=s.xp/engine.xpTarget*100+'%';$('xp').textContent=h?'Nivel '+s.level+' · '+s.xp+' / '+engine.xpTarget+' EXP':'Compra de prueba para comenzar';$('attack').textContent=h?engine.attack:'—';$('health').textContent=h?Math.floor(s.hp)+' / '+engine.maxHp:'—';$('reward').textContent=engine.reward+' Blez';$('cost').textContent=format(engine.cost)+' Blez';$('pending').textContent=format(s.pending)+' Blez';$('claim').disabled=!s.pending;$('upgrade').disabled=!h||s.coins<engine.cost;$('pause').disabled=!h;$('pause').textContent=s.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',s.paused?'Reanudar combate':'Pausar combate');$('camp-coins').textContent=format(s.coins)+' Blez';$('offline-rate').textContent=h?'Estimación: '+Math.floor(engine.offlineRate()*3600)+' Blez / hora':'Compra un héroe para activar el progreso.';$('hint').textContent=s.unlocked>s.zone?'Nueva zona disponible. Abre el mapa para viajar.':'Derrota al jefe de cada zona para abrir el siguiente camino.';
$('hero-list').innerHTML=C.heroes.map(h=>'<article class="hero-card"><span class="symbol">'+h.symbol+'</span><small>'+h.className.toUpperCase()+'</small><h2>'+h.name+'</h2><p>'+h.desc+'</p><div class="class-stats">⚔ '+h.attack+' ATAQUE &nbsp; ♥ '+h.hp+' VIDA</div><button class="'+(s.heroId===h.id?'secondary':'primary')+'" data-hero="'+h.id+'">'+(s.heroId===h.id?'Héroe activo':s.owned.includes(h.id)?'Equipar héroe':'Comprar · '+format(h.price)+' Blez')+'</button></article>').join('');for(const b of document.querySelectorAll('[data-hero]')){portrait(b.closest('.hero-card').querySelector('.symbol'),b.dataset.hero);b.disabled=s.heroId===b.dataset.hero;b.onclick=()=>chooseHero(b.dataset.hero);}
sheet();$('zone-list').innerHTML=C.zones.map((z,i)=>'<article class="zone-card"><span class="zone-icon map-thumb"><canvas width="144" height="130" aria-label="'+z.name+'"></canvas></span><div><small>ZONA 0'+(i+1)+'</small><h2>'+z.name+'</h2><p>'+z.boss+' · '+z.reward+' Blez / enemigo</p></div><button class="secondary" data-zone="'+i+'" '+(i>s.unlocked||i===s.zone?'disabled':'')+'>'+(i>s.unlocked?'🔒':i===s.zone?'Aquí':'Viajar')+'</button></article>').join('');for(const b of document.querySelectorAll('[data-zone]')){const c=b.closest('.zone-card').querySelector('canvas');c.getContext('2d').imageSmoothingEnabled=false;c.getContext('2d').drawImage(PixelScene.zoneThumbnail(Number(b.dataset.zone)),0,0,c.width,c.height);b.onclick=()=>{if(engine.travel(Number(b.dataset.zone))){persist();tab('battle');toast('Entrando en '+engine.zone.name);}};}}
$('pause').onclick=()=>{engine.s.paused=!engine.s.paused;persist();render();};$('upgrade').onclick=()=>{if(engine.upgrade()){persist();render();toast('Arma mejorada · +4 ataque');}};$('claim').onclick=()=>{const n=engine.claim();persist();render();toast('Reclamaste '+format(n)+' Blez');};
let lastTick=performance.now();setInterval(()=>{const now=performance.now();if(document.hidden||now-lastTick<1150)return;lastTick=now;const event=engine.tick();if(event.type==='hit'||event.type==='kill')scene.impact(event);if(event.type==='kill'){$('loot').textContent='+'+event.reward+' Blez · '+(event.boss?'Jefe derrotado':'Enemigo derrotado');if(event.unlocked)toast('¡Nueva zona desbloqueada!');}if(event.type==='rest'){$('loot').textContent='El héroe se recupera. Mejora su arma.';toast('Tu héroe se recuperó para intentarlo de nuevo.');}render();persist();},250);
let hiddenAt=null;document.addEventListener('visibilitychange',()=>{if(document.hidden){hiddenAt=Date.now();persist();}else{if(hiddenAt&&engine.hero&&!engine.s.paused){const seconds=Math.min(C.offlineCap,Math.max(0,(Date.now()-hiddenAt)/1000));if(seconds>=30)engine.s.pending+=Math.floor(seconds*engine.offlineRate());}hiddenAt=null;lastTick=performance.now();persist();render();}});addEventListener('pagehide',persist);render();if(!engine.hero)welcome();else if(engine.s.pending)toast('Tu héroe reunió monedas. ¡Abre el cofre!');
