(function(root){'use strict';const C=typeof module!=='undefined'?require('./config.js'):root.GameConfig;
function initial(){return {version:1,heroId:null,owned:[],coins:0,pending:0,kills:0,level:1,xp:0,weapon:0,zone:0,unlocked:0,wave:1,paused:false,hp:0,enemyHp:0,lastSeen:Date.now()};}
class Engine{constructor(saved){this.s=initial();if(saved&&saved.version===1){for(const k of ['coins','pending','kills','xp','weapon'])this.s[k]=Number.isFinite(saved[k])?Math.max(0,Math.floor(saved[k])):0;this.s.level=Math.min(1000,Math.max(1,Number.isFinite(saved.level)?Math.floor(saved.level):1));this.s.unlocked=Math.min(3,Math.max(0,Number.isInteger(saved.unlocked)?saved.unlocked:0));this.s.zone=Math.min(this.s.unlocked,Math.max(0,Number.isInteger(saved.zone)?saved.zone:0));this.s.wave=Math.min(10,Math.max(1,Number.isInteger(saved.wave)?saved.wave:1));this.s.owned=C.heroes.filter(h=>Array.isArray(saved.owned)&&saved.owned.includes(h.id)).map(h=>h.id);this.s.heroId=this.s.owned.includes(saved.heroId)?saved.heroId:null;this.s.paused=saved.paused===true;const seen=Number.isFinite(saved.lastSeen)?saved.lastSeen:Date.now();if(this.s.heroId&&!this.s.paused){let seconds=Math.min(C.offlineCap,Math.max(0,(Date.now()-seen)/1000));if(seconds>=30)this.s.pending+=Math.floor(seconds*this.offlineRate());}}this.resetFight();}
get hero(){return C.heroes.find(h=>h.id===this.s.heroId);}get zone(){return C.zones[this.s.zone];}get attack(){return this.hero?this.hero.attack+(this.s.level-1)*2+this.s.weapon*4:0;}get maxHp(){return this.hero?this.hero.hp+(this.s.level-1)*10:0;}get enemyMax(){return this.zone.hp*(this.s.wave===10?4:1)*(1+(this.s.wave-1)*.08);}get reward(){return this.zone.reward*(this.s.wave===10?5:1);}get cost(){return Math.floor(20*Math.pow(1.5,this.s.weapon));}get xpTarget(){return this.s.level*30;}get enemyName(){return this.s.wave===10?this.zone.boss:this.zone.enemy;}
resetFight(){this.s.hp=this.maxHp;this.s.enemyHp=this.enemyMax;}acquire(id){if(!C.heroes.some(h=>h.id===id))return false;if(!this.s.owned.includes(id))this.s.owned.push(id);this.s.heroId=id;this.resetFight();return true;}
buy(id){const h=C.heroes.find(h=>h.id===id);if(!h)return false;if(this.s.owned.includes(id))return this.acquire(id);if(this.s.coins<h.price)return false;this.s.coins-=h.price;return this.acquire(id);}
demoCredit(){if(!C.demo)return false;this.s.coins+=5000;return true;}
quoteWithdrawal(amount){if(!Number.isSafeInteger(amount)||amount<=0)return null;return {blez:amount,ton:amount/C.blezPerTon,covered:amount<=this.s.coins,demo:true};}
upgrade(){if(!this.hero||this.s.coins<this.cost)return false;this.s.coins-=this.cost;this.s.weapon++;return true;}
travel(index){if(!Number.isInteger(index)||index<0||index>this.s.unlocked||index>=C.zones.length)return false;this.s.zone=index;this.s.wave=1;this.resetFight();return true;}
claim(){const amount=this.s.pending;this.s.coins+=amount;this.s.pending=0;return amount;}
offlineRate(){if(!this.hero)return 0;const seconds=Math.ceil(this.enemyMax/this.attack)*1.2;return Math.min(2,this.reward/Math.max(8,seconds))*.5;}
tick(){if(!this.hero||this.s.paused)return {type:'idle'};this.s.enemyHp=Math.max(0,this.s.enemyHp-this.attack);if(this.s.enemyHp===0){const reward=this.reward;const boss=this.s.wave===10;this.s.coins+=reward;this.s.kills++;this.s.xp+=boss?20:8;while(this.s.xp>=this.xpTarget&&this.s.level<1000){this.s.xp-=this.xpTarget;this.s.level++;}let unlocked=false;if(boss){if(this.s.zone===this.s.unlocked&&this.s.unlocked<3){this.s.unlocked++;unlocked=true;}this.s.wave=1;}else this.s.wave++;this.resetFight();return {type:'kill',reward,boss,unlocked};}this.s.hp=Math.max(0,this.s.hp-this.zone.damage*(this.s.wave===10?2:1));if(!this.s.hp){this.resetFight();return {type:'rest'};}return {type:'hit',damage:this.attack};}
save(){return {...this.s,lastSeen:Date.now()};}}
if(typeof module!=='undefined')module.exports={Engine,initial};else root.IdleEngine=Engine;})(globalThis);
