(function(root){'use strict';const C=typeof module!=='undefined'?require('./config.js'):root.GameConfig,E=typeof module!=='undefined'?require('./equipment'):root.GameEquipment;
function starterBag(){const bag=Array(20).fill(null);C.items.filter(item=>!item.variantOf&&(!item.price||item.id==='health-potion')).slice(0,20).forEach((item,i)=>bag[i]={itemId:item.id,quantity:item.kind==='potion'?5:1});return bag.map(slot=>slot?E.normalize(slot):null);}
function initial(){return {version:1,gearSchema:1,classSchema:1,classKitAssigned:false,bag:starterBag(),bagExpansions:0,marketRevision:0,gramUnits:0,gramSalesUnits:0,equipment:{},potionLoadout:{},mana:0,heroId:null,owned:[],coins:0,pending:0,kills:0,level:1,xp:0,weapon:0,zone:0,unlocked:0,wave:1,completed:false,recovering:false,paused:false,hp:0,enemyHp:0,lastSeen:Date.now()};}
class Engine{constructor(saved,random=Math.random){this.random=random;this.s=initial();this.s.marketRevision=Number.isSafeInteger(saved?.marketRevision)?Math.max(0,saved.marketRevision):0;if(saved&&saved.version===1){for(const k of ['coins','pending','kills','xp','weapon','gramUnits','gramSalesUnits'])this.s[k]=Number.isFinite(saved[k])?Math.max(0,Math.floor(saved[k])):0;this.s.level=Math.min(1000,Math.max(1,Number.isFinite(saved.level)?Math.floor(saved.level):1));this.s.unlocked=Math.min(C.zones.length-1,Math.max(0,Number.isInteger(saved.unlocked)?saved.unlocked:0));this.s.zone=Math.min(this.s.unlocked,Math.max(0,Number.isInteger(saved.zone)?saved.zone:0));this.s.wave=Math.min(10,Math.max(1,Number.isInteger(saved.wave)?saved.wave:1));this.s.owned=C.heroes.filter(h=>Array.isArray(saved.owned)&&saved.owned.includes(h.id)).map(h=>h.id);this.s.heroId=this.s.owned.includes(saved.heroId)?saved.heroId:null;this.s.completed=saved.completed===true&&this.s.zone===C.zones.length-1&&this.s.wave===10;this.loadBag(saved);this.s.paused=saved.paused===true;const seen=Number.isFinite(saved.lastSeen)?saved.lastSeen:Date.now();if(this.s.heroId&&!this.s.paused&&!this.s.completed){let seconds=Math.min(C.offlineCap,Math.max(0,(Date.now()-seen)/1000));if(seconds>=30)this.s.pending+=Math.floor(seconds*this.offlineRate());}}this.resetFight();if(saved&&saved.version===1){this.s.potionLoadout={};for(const resource of ['health','mana']){const id=saved.potionLoadout?.[resource],item=C.items.find(i=>i.id===id&&i.kind==='potion'&&i.resource===resource);if(item)this.s.potionLoadout[resource]=id;}if(Number.isFinite(saved.mana))this.s.mana=Math.min(this.maxMana,Math.max(0,Math.floor(saved.mana)));}if(saved&&saved.version===1&&this.hero&&Number.isFinite(saved.hp)){this.s.hp=Math.min(this.maxHp,Math.max(0,Math.floor(saved.hp)));if(!this.s.hp||saved.recovering===true)this.startRecovery();}}
get bagCapacity(){return 20+this.s.bagExpansions*2;}
get bagCost(){return 200*(this.s.bagExpansions+1);}
itemAt(index){const slot=this.s.bag[index];return slot?E.stats(slot):null;}
loadBag(saved){this.s.bagExpansions=Number.isSafeInteger(saved.bagExpansions)?Math.max(0,Math.min(990,saved.bagExpansions)):0;if(Array.isArray(saved.bag)){this.s.bag=Array.from({length:this.bagCapacity},(_,index)=>{const slot=saved.bag[index],item=slot&&C.items.find(i=>i.id===slot.itemId);return item&&Number.isInteger(slot.quantity)&&slot.quantity>0?{itemId:item.id,quantity:Math.min(item.stack||1,slot.quantity),level:Number.isInteger(slot.level)?Math.max(1,Math.min(1000,slot.level)):1,rarity:C.rarities[slot.rarity]?slot.rarity:item.rarity,marketable:item.kind!=='potion'&&slot.marketable===true,affixes:slot.affixes,instanceId:slot.instanceId}:null;});}else this.s.bag=starterBag().concat(Array(this.bagCapacity-20).fill(null));if(saved.classSchema!==1&&this.s.heroId)this.convertLegacyGear(this.s.heroId);this.s.bag=this.s.bag.map(slot=>slot?E.normalize(slot):null);this.s.classKitAssigned=saved.classKitAssigned===true||!!this.s.heroId;this.s.classSchema=1;this.s.equipment={};for(const kind of C.equipmentSlots){const index=saved.equipment&&saved.equipment[kind],item=Number.isInteger(index)&&index>=0?this.itemAt(index):null;if(item&&item.kind===kind&&item.hero===this.s.heroId)this.s.equipment[kind]=index;}if(saved.gearSchema!==1&&Array.isArray(saved.bag)){for(const id of ['iron-helmet','leather-gloves','guard-shield','spell-book','forest-quiver','silver-necklace','dawn-ring'])this.addItem(id);}this.s.gearSchema=1;}
convertLegacyGear(hero){for(const slot of this.s.bag){if(!slot)continue;const variant=C.items.find(item=>item.variantOf===slot.itemId&&item.hero===hero);if(variant)slot.itemId=variant.id;}}
gearBonus(stat){return Object.values(this.s.equipment).reduce((total,index)=>{const item=this.itemAt(index);return total+(item&&item.hero===this.s.heroId?item[stat]||0:0);},0);}
equip(index){if(!Number.isInteger(index)||index<0||index>=this.bagCapacity||!this.hero)return false;const item=this.itemAt(index);if(!item||item.kind==='potion'||item.hero!==this.s.heroId)return false;this.s.equipment[item.kind]=index;this.s.hp=Math.min(this.s.hp,this.maxHp);return true;}
unequip(index){if(!Number.isInteger(index)||index<0)return false;const item=this.itemAt(index);if(!item||this.s.equipment[item.kind]!==index)return false;delete this.s.equipment[item.kind];this.s.hp=Math.min(this.s.hp,this.maxHp);return true;}
sellItem(index){if(!Number.isInteger(index)||index<0||index>=this.bagCapacity)return 0;const item=this.itemAt(index);if(!item||item.kind==='potion'||item.marketable||Object.values(this.s.equipment).includes(index))return 0;const price=C.vendorPrices[item.rarity];if(!price)return 0;this.s.bag[index]=null;this.s.coins+=price;return price;}
expandBag(){const cost=this.bagCost;if(this.s.coins<cost||this.s.bagExpansions>=990)return false;this.s.coins-=cost;this.s.bagExpansions++;this.s.bag.push(null,null);return true;}
addItem(id,quantity=1,metadata={}){const item=C.items.find(i=>i.id===id);if(!item||!Number.isSafeInteger(quantity)||quantity<=0)return quantity;let remaining=quantity,limit=item.stack||1;for(const slot of this.s.bag){if(slot&&slot.itemId===id&&slot.quantity<limit){const added=Math.min(remaining,limit-slot.quantity);slot.quantity+=added;remaining-=added;if(!remaining)return 0;}}for(let index=0;index<this.bagCapacity;index++){if(!this.s.bag[index]){const added=Math.min(remaining,limit);this.s.bag[index]={itemId:id,quantity:added,level:Number.isInteger(metadata.level)?Math.max(1,Math.min(1000,metadata.level)):1,rarity:C.rarities[metadata.rarity]?metadata.rarity:item.rarity,marketable:item.kind!=='potion'&&metadata.marketable===true,affixes:metadata.affixes,instanceId:metadata.instanceId};this.s.bag[index]=E.normalize(this.s.bag[index],this.random);remaining-=added;if(!remaining)return 0;}}return remaining;}
get maxMana(){return this.hero?100+(this.s.level-1)*5:0;}
potionCount(id){return this.s.bag.reduce((sum,slot)=>sum+(slot?.itemId===id?slot.quantity:0),0);}
buyPotion(id,quantity=1){const item=C.items.find(i=>i.id===id&&i.kind==='potion');if(!item||!Number.isSafeInteger(quantity)||quantity<1||quantity>100||this.s.coins<item.price*quantity)return false;const space=this.s.bag.reduce((sum,slot)=>sum+(!slot?100:slot.itemId===id?100-slot.quantity:0),0);if(space<quantity)return false;this.addItem(id,quantity);this.s.coins-=item.price*quantity;return true;}
equipPotion(index){const item=this.itemAt(index);if(!this.hero||item?.kind!=='potion')return false;this.s.potionLoadout[item.resource]=item.id;return true;}
unequipPotion(resource){if(!this.s.potionLoadout[resource])return false;delete this.s.potionLoadout[resource];return true;}
usePotion(index){const item=this.itemAt(index);if(!this.hero||this.s.recovering||this.s.hp<=0||!item||item.kind!=='potion')return false;const key=item.resource==='mana'?'mana':'hp',max=key==='mana'?this.maxMana:this.maxHp;if(this.s[key]>=max)return false;this.s[key]=Math.min(max,this.s[key]+item.heal);this.s.bag[index].quantity--;if(!this.s.bag[index].quantity)this.s.bag[index]=null;return true;}
autoPotions(){const used=[];for(const resource of ['health','mana']){const key=resource==='health'?'hp':'mana',max=resource==='health'?this.maxHp:this.maxMana;if(this.s[key]>max*(resource==='health'?.5:.3))continue;const id=this.s.potionLoadout[resource],index=this.s.bag.findIndex(slot=>slot?.itemId===id);if(index>=0&&this.usePotion(index))used.push(C.items.find(i=>i.id===id).name);}return used;}
get lootTable(){return C.lootTables[Math.min(C.lootTables.length-1,Math.floor(this.s.zone/2))];}
rollEquipmentDrop(boss=false){if(!this.hero||this.random()*100>=C.equipmentDrop[boss?'boss':'mob'])return null;const table=this.lootTable,roll=this.random()*100;let cumulative=0,rarity=null;for(const [name,chance] of Object.entries(table.rarity)){cumulative+=chance;if(roll<cumulative){rarity=name;break;}}if(!rarity)return null;const pool=C.items.filter(i=>i.kind!=='potion'&&i.hero===this.s.heroId),item=pool[Math.min(pool.length-1,Math.floor(this.random()*pool.length))];const marketable=this.random()*100<C.marketableDrop[boss?'boss':'mob'];const stored=this.addItem(item.id,1,{level:table.level,rarity,marketable})===0;return {itemId:item.id,name:item.name,rarity,level:table.level,marketable,stored};}
get speed(){return Math.min(100,this.gearBonus('speed'));}get critChance(){return Math.min(75,this.gearBonus('critChance'));}get critDamage(){return 50+Math.min(200,this.gearBonus('critDamage'));}get actionInterval(){return 600/(1+this.speed/100);}
get hero(){return C.heroes.find(h=>h.id===this.s.heroId);}get zone(){return C.zones[this.s.zone];}get attack(){return this.hero?this.hero.attack+(this.s.level-1)*2+this.s.weapon*4+this.gearBonus('attack'):0;}get maxHp(){return this.hero?this.hero.hp+(this.s.level-1)*10+this.gearBonus('hp'):0;}get mobCount(){return this.zone.mobs||1;}
isBoss(index){return this.s.wave===10&&index===0;}
mobMax(index){return this.zone.hp*(this.isBoss(index)?4:1)*(1+(this.s.wave-1)*.08);}
get enemyMax(){return Array.from({length:this.mobCount},(_,i)=>this.mobMax(i)).reduce((a,b)=>a+b,0);}
get target(){return this.mobHps?Math.max(0,this.mobHps.findIndex(hp=>hp>0)):0;}
get aliveMobs(){return this.mobHps?this.mobHps.filter(hp=>hp>0).length:this.mobCount;}
resetEnemies(){this.mobHps=Array.from({length:this.mobCount},(_,i)=>this.mobMax(i));this.s.enemyHp=this.enemyMax;}get reward(){return this.zone.reward*(this.s.wave===10?5+this.mobCount-1:this.mobCount);}get cost(){return Math.floor(20*Math.pow(1.5,this.s.weapon));}get xpTarget(){return this.s.level*30;}get enemyName(){return this.s.wave===10?this.zone.boss:this.zone.enemy;}
get skillName(){return this.hero?({warrior:"Corte del Guardián",ranger:"Flecha perforante",mage:"Estallido arcano"}[this.hero.id]):"";}
get enemyAttack(){return Math.max(1,this.zone.damage-this.gearBonus('defense'))*(this.mobHps?this.mobHps.reduce((sum,hp,i)=>sum+(hp>0?(this.isBoss(i)?2:1):0),0):this.mobCount);}
resetFight(){this.s.hp=this.maxHp;this.s.mana=this.maxMana;this.resetEnemies();this.charge=0;this.restTicks=0;this.s.recovering=false;this.beginJourney();}startRecovery(){this.s.wave=1;this.s.completed=false;this.s.recovering=true;this.resetEnemies();this.phase='recovery';this.charge=0;this.restTicks=3;}
beginJourney(){this.travelTicks=4;this.phase=this.s.completed?"complete":"walk";}
get stage(){return this.s.zone*10+this.s.wave;}
get totalStages(){return C.zones.length*10;}
restart(){if(!this.hero)return false;this.s.completed=false;this.s.zone=0;this.s.wave=1;this.s.paused=false;this.resetFight();return true;}
acquire(id){if(!C.heroes.some(h=>h.id===id))return false;if(!this.s.owned.includes(id))this.s.owned.push(id);this.s.heroId=id;if(!this.s.classKitAssigned){this.convertLegacyGear(id);this.s.classKitAssigned=true;}for(const [kind,index] of Object.entries(this.s.equipment)){const item=this.itemAt(index);if(item&&item.hero&&item.hero!==id)delete this.s.equipment[kind];}this.resetFight();return true;}
buy(id){const h=C.heroes.find(h=>h.id===id);if(!h)return false;if(this.s.owned.includes(id))return this.acquire(id);if(this.s.coins<h.price)return false;this.s.coins-=h.price;return this.acquire(id);}
demoCredit(){if(!C.demo)return false;this.s.coins+=5000;return true;}
quoteWithdrawal(amount){if(!Number.isSafeInteger(amount)||amount<=0)return null;const ton=amount/C.blezPerTon,feeTon=ton*C.withdrawalFeePercent/100;return {blez:amount,ton,feeTon,netTon:ton-feeTon,covered:amount<=this.s.coins,demo:true};}
quoteGramWithdrawal(amount){const units=C.currency.toUnits(amount);if(!units)return null;const feeUnits=C.currency.fee(units,C.withdrawalFeePercent);return {units,feeUnits,netUnits:units-feeUnits,covered:units<=this.s.gramUnits,demo:true};}
upgrade(){if(!this.hero||this.s.coins<this.cost)return false;this.s.coins-=this.cost;this.s.weapon++;return true;}
travel(index){if(!Number.isInteger(index)||index<0||index>this.s.unlocked||index>=C.zones.length)return false;this.s.completed=false;this.s.zone=index;this.s.wave=1;this.resetFight();return true;}
claim(){const amount=this.s.pending;this.s.coins+=amount;this.s.pending=0;return amount;}
offlineRate(){if(!this.hero||this.s.completed)return 0;const expectedAttack=this.attack*(1+this.critChance/100*this.critDamage/100),seconds=2.4+Math.ceil(this.enemyMax/expectedAttack)*(this.actionInterval+600)/1000;return Math.min(2,this.reward/Math.max(8,seconds))*.5;}
tick(){
this.lastPotions=[];
if(!this.hero||this.s.paused||this.s.completed)return {type:'idle'};
if(!this.restTicks)this.lastPotions=this.autoPotions();
if(!this.restTicks&&(this.phase==='walk'||this.phase==='approach')){this.travelTicks--;if(this.travelTicks===0){this.phase='hero';return {type:'encounter',enemy:this.enemyName};}this.phase=this.travelTicks<=2?'approach':'walk';return {type:this.phase};}
if(this.restTicks>0){const before=this.s.hp;this.restTicks--;this.s.hp=Math.min(this.maxHp,this.s.hp+Math.ceil(this.maxHp/3));if(!this.restTicks){this.s.hp=this.maxHp;this.s.mana=this.maxMana;this.resetEnemies();this.s.recovering=false;this.beginJourney();this.charge=0;}return {type:'recover',remaining:this.restTicks,heal:this.s.hp-before};}
if(this.phase==='enemy'){const damage=this.enemyAttack;this.s.hp=Math.max(0,this.s.hp-damage);this.phase='hero';if(!this.s.hp){const fromStage=this.s.wave;this.startRecovery();return {type:'rest',damage,fromStage,zone:this.s.zone};}return {type:'enemyHit',damage,boss:this.s.wave===10};}
this.charge++;const ready=this.charge>=4,skill=ready&&this.s.mana>=10;if(ready)this.charge=0;if(skill)this.s.mana-=10;const critical=this.critChance>0&&this.random()*100<this.critChance;const rawDamage=skill?Math.ceil(this.attack*({warrior:1.8,ranger:2,mage:2.2}[this.hero.id])):this.attack,damage=critical?Math.ceil(rawDamage*(1+this.critDamage/100)):rawDamage;if(skill)this.charge=0;
const target=this.target;this.mobHps[target]=Math.max(0,this.mobHps[target]-damage);this.s.enemyHp=this.mobHps.reduce((a,b)=>a+b,0);const equipmentDrop=this.mobHps[target]===0?this.rollEquipmentDrop(this.isBoss(target)):null;
if(this.s.enemyHp===0){const reward=this.reward,boss=this.s.wave===10,enemy=this.enemyName,zone=this.s.zone,count=this.mobCount;const potionStored=this.addItem('health-potion',1)===0;this.s.coins+=reward;this.s.kills+=count;this.s.xp+=boss?20+(count-1)*8:count*8;while(this.s.xp>=this.xpTarget&&this.s.level<1000){this.s.xp-=this.xpTarget;this.s.level++;}let unlocked=false;if(boss){if(this.s.zone===this.s.unlocked&&this.s.unlocked<C.zones.length-1){this.s.unlocked++;unlocked=true;}if(this.s.zone<C.zones.length-1){this.s.zone++;this.s.wave=1;}else this.s.completed=true;}else this.s.wave++;this.s.hp=Math.min(this.maxHp,this.s.hp+Math.ceil(this.maxHp*.12));this.resetEnemies();this.beginJourney();return {type:'kill',equipmentDrop,potionStored,target,count,zone,completed:this.s.completed,damage,critical,skill,move:skill?this.skillName:null,reward,boss,enemy,unlocked};}
this.phase='enemy';return {type:'hit',equipmentDrop,target,defeated:this.mobHps[target]===0,damage,critical,skill,move:skill?this.skillName:null};}

save(){return {...this.s,bag:this.s.bag.map(slot=>slot?{...slot,...(slot.affixes?{affixes:slot.affixes.map(a=>({...a}))}:{})}:null),equipment:{...this.s.equipment},potionLoadout:{...this.s.potionLoadout},lastSeen:Date.now()};}}
if(typeof module!=='undefined')module.exports={Engine,initial};else root.IdleEngine=Engine;})(globalThis);
