(function(root){'use strict';const C=typeof module!=='undefined'?require('./config'):root.GameConfig;
const labels={attack:'Ataque',hp:'HP',defense:'Defensa',speed:'Velocidad de ataque',critChance:'Prob. crítico',critDamage:'Daño crítico'},percent=new Set(['speed','critChance','critDamage']);
const tiers={'Común':{count:[1,2],quality:[10,45],power:1},'Poco común':{count:[1,3],quality:[20,55],power:1.35},'Raro':{count:[2,4],quality:[35,70],power:2},'Épico':{count:[3,5],quality:[50,90],power:3.5},'Legendario':{count:[4,6],quality:[70,100],power:5.5}};
function seeded(seed){let n=2166136261;for(const ch of seed)n=Math.imul(n^ch.charCodeAt(0),16777619);return()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function roll(level,rarity,random=Math.random){const tier=tiers[rarity]||tiers['Común'],keys=Object.keys(labels);for(let i=keys.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[keys[i],keys[j]]=[keys[j],keys[i]];}const count=tier.count[0]+Math.floor(random()*(tier.count[1]-tier.count[0]+1)),scale=1+(Math.max(1,level)-1)*.12;return keys.slice(0,count).map(stat=>{const quality=tier.quality[0]+Math.floor(random()*(tier.quality[1]-tier.quality[0]+1)),strength=tier.power*(.5+quality/100),base={attack:2,hp:12,defense:1,speed:2,critChance:1.5,critDamage:4}[stat],raw=base*strength*(percent.has(stat)?Math.sqrt(scale):scale),value=percent.has(stat)?Math.max(.1,Math.min(stat==='critDamage'?100:30,Math.round(raw*10)/10)):Math.max(1,Math.floor(raw));return {stat,value,quality};});}
function normalize(slot,random=Math.random){const base=C.items.find(i=>i.id===slot.itemId);if(!base||base.kind==='potion')return {...slot};const seen=new Set(),valid=Array.isArray(slot.affixes)&&slot.affixes.length>0&&slot.affixes.length<=6&&slot.affixes.every(a=>{if(!a||!labels[a.stat]||seen.has(a.stat)||!Number.isFinite(a.value)||a.value<=0||a.value>1000000||!Number.isInteger(a.quality)||a.quality<1||a.quality>100)return false;seen.add(a.stat);return true;});return {...slot,instanceId:typeof slot.instanceId==='string'?slot.instanceId:(root.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)),affixes:valid?slot.affixes.map(a=>({...a})):roll(slot.level||1,slot.rarity||base.rarity,random)};}
function stats(slot){const base=C.items.find(i=>i.id===slot.itemId);if(!base)return null;const level=slot.level||1,rarity=slot.rarity||base.rarity,factor=(1+(level-1)*.15)*(C.rarities[rarity]||1),result={...base,level,rarity,marketable:base.kind!=='potion'&&slot.marketable===true,attack:Math.floor((base.attack||0)*factor),hp:Math.floor((base.hp||0)*factor),defense:Math.floor((base.defense||0)*factor),speed:0,critChance:0,critDamage:0,affixes:(slot.affixes||[]).map(a=>({...a})),instanceId:slot.instanceId};for(const affix of result.affixes)if(labels[affix.stat])result[affix.stat]=Number(((result[affix.stat]||0)+affix.value).toFixed(1));return result;}
function qualityLabel(q){return q<35?'Baja':q<65?'Media':q<90?'Alta':'Excelente';}
function summary(piece){return Object.keys(labels).filter(k=>piece[k]>0).map(k=>labels[k]+' +'+piece[k]+(percent.has(k)?'%':'')).join(' · ');}
const api={labels,percent,tiers,seeded,roll,normalize,stats,qualityLabel,summary};for(const listing of C.marketCatalog)listing.item=normalize(listing.item,seeded(listing.id));if(typeof module!=='undefined')module.exports=api;else root.GameEquipment=api;
})(globalThis);
