'use strict';
(()=>{
let token=null,player='',offers=[],view='offers',busy=false,connected=false,wasPaused=false,refreshTimer;
const dialog=$('market-modal'),content=$('market-content'),status=$('market-status');
function session(){if(token)return token;token=localStorage.getItem('etherial-market-session');if(!token){token=crypto.randomUUID();localStorage.setItem('etherial-market-session',token);}return token;}
async function api(method,data){const response=await fetch('/api/market',{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+session()},...(data?{body:JSON.stringify(data)}:{})});let result;try{result=await response.json();}catch{throw new Error('El mercado compartido necesita el servidor del juego. Todavía no está disponible en esta página.');}if(!response.ok){if(result.state){apply(result);throw new Error('Partida sincronizada. Revisa tu mochila y vuelve a intentar.');}throw new Error(result.error||'No se pudo conectar con el mercado.');}return result;}
function apply(result){engine.s.bag=result.state.bag;engine.s.coins=result.state.coins;engine.s.marketRevision=result.revision;engine.s.equipment=result.state.equipment;player=result.player||player;bagSignature='';persist();render();}
async function act(action,extra={}){if(busy)return;busy=true;draw();try{const snapshot=engine.save();snapshot.paused=wasPaused;apply(await api('POST',{action,revision:engine.s.marketRevision,state:snapshot,...extra}));offers=(await api('GET')).listings;connected=true;status.textContent='Jugador '+player+' · '+format(engine.s.coins)+' Blez · Sin comisión';if(action==='publish')view='mine';toast(action==='buy'?'Equipo comprado y guardado':action==='cancel'?'Equipo recuperado':action==='publish'?'Oferta publicada':'Mercado actualizado');}catch(error){status.textContent=error.message;}finally{busy=false;draw();}}
function pieceCard(slot){const base=C.items.find(i=>i.id===slot.itemId),piece={...base,level:slot.level||1,rarity:slot.rarity||base.rarity},card=document.createElement('article');card.className='market-card';card.setAttribute('data-rarity',piece.rarity);const icon=document.createElement('div');icon.className='market-icon';bagIcon(icon,piece.icon,piece.rarity,piece.level);const title=document.createElement('h2');title.textContent=piece.name;const meta=document.createElement('small');meta.textContent=piece.rarity+' · Nv. '+piece.level+' · '+C.heroes.find(h=>h.id===piece.hero).className;const stats=document.createElement('p'),factor=(1+(piece.level-1)*.15)*C.rarities[piece.rarity];stats.textContent='⚔ '+Math.floor((piece.attack||0)*factor)+' · ♥ '+Math.floor((piece.hp||0)*factor)+' · ◈ '+Math.floor((piece.defense||0)*factor);card.append(icon,title,meta,stats);return card;}
function draw(){content.replaceChildren();for(const id of ['market-offers','market-sell','market-mine','market-refresh'])$(id).disabled=busy||(id!=='market-refresh'&&!connected);if(!connected)return;if(view==='sell'){const hint=document.createElement('p');hint.textContent='Selecciona un precio en Blez. Desequipa el objeto para publicarlo. Puedes mantener hasta 20 ofertas activas.';content.append(hint);let count=0;engine.s.bag.forEach((slot,index)=>{const piece=engine.itemAt(index);if(!piece||piece.kind==='potion')return;count++;const card=pieceCard(slot),equipped=Object.values(engine.s.equipment).includes(index);const form=document.createElement('form'),label=document.createElement('label');label.textContent='Precio en Blez';const price=document.createElement('input');price.type='number';price.min='1';price.max='1000000000';price.step='1';price.required=true;price.value='100';price.setAttribute('aria-label','Precio de '+piece.name+' en Blez');const submit=document.createElement('button');submit.className='primary';submit.type='submit';submit.textContent=equipped?'Desequipa para vender':'Publicar oferta';submit.disabled=busy||equipped;form.onsubmit=event=>{event.preventDefault();return act('publish',{index,price:Number(price.value)});};label.append(price);form.append(label,submit);card.append(form);content.append(card);});if(!count)empty('No tienes equipo para vender.');return;}
const list=offers.filter(l=>view==='mine'?l.mine:!l.mine);for(const listing of list){const card=pieceCard(listing.item),price=document.createElement('b');price.textContent=format(listing.price)+' Blez';const seller=document.createElement('p');seller.textContent='Vendedor '+listing.seller;const button=document.createElement('button');button.className='secondary';button.textContent=listing.mine?'Retirar y recuperar equipo':'Comprar · '+format(listing.price)+' Blez';button.disabled=busy||(!listing.mine&&(engine.s.coins<listing.price||!engine.s.bag.some(s=>!s)));button.onclick=()=>act(listing.mine?'cancel':'buy',{id:listing.id});card.append(price,seller,button);content.append(card);}if(!list.length)empty(view==='mine'?'No tienes ventas activas. Los Blez de ventas completadas se cobran al actualizar.':'Todavía no hay ofertas de otros jugadores.');}
function empty(text){const p=document.createElement('p');p.textContent=text;content.append(p);}
$('open-market').onclick=async()=>{if(dialog.open)return;wasPaused=engine.s.paused;engine.s.paused=true;connected=false;view='offers';status.textContent='Conectando con el mercado…';dialog.showModal();draw();await act('sync');if(dialog.open)refreshTimer=setInterval(async()=>{if(busy||view==='sell'||!dialog.open||!connected)return;try{offers=(await api('GET')).listings;draw();}catch{status.textContent='Conexión perdida. Pulsa actualizar para reintentar.';}},8000);};
function closeMarket(){clearInterval(refreshTimer);engine.s.paused=wasPaused;persist();render();}
$('close-market').onclick=()=>{if(busy)return;dialog.close();closeMarket();};dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();});dialog.addEventListener('close',closeMarket);
$('market-offers').onclick=()=>{view='offers';draw();};$('market-sell').onclick=()=>{view='sell';draw();};$('market-mine').onclick=()=>{view='mine';draw();};$('market-refresh').onclick=()=>act('sync');
})();
