'use strict';
(()=>{
let token=null,player='',offers=[],view='offers',busy=false,connected=false,wasPaused=false,refreshTimer;
const dialog=$('market-modal'),content=$('market-content'),status=$('market-status');
function session(){if(token)return token;token=localStorage.getItem('etherial-market-session');if(!token){token=crypto.randomUUID();localStorage.setItem('etherial-market-session',token);}return token;}
async function api(method,data){const response=await fetch('/api/market',{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+session()},...(data?{body:JSON.stringify(data)}:{})});let result;try{result=await response.json();}catch{throw new Error('El mercado compartido necesita el servidor del juego. Todavía no está disponible en esta página.');}if(!response.ok){if(result.state){apply(result);throw new Error('Partida sincronizada. Revisa tu mochila y vuelve a intentar.');}throw new Error(result.error||'No se pudo conectar con el mercado.');}return result;}
function apply(result){engine.s.bag=result.state.bag;engine.s.coins=result.state.coins;engine.s.gramUnits=result.state.gramUnits||0;engine.s.gramSalesUnits=result.state.gramSalesUnits||0;engine.s.marketRevision=result.revision;engine.s.equipment=result.state.equipment;player=result.player||player;bagSignature='';persist();render();}
async function act(action,extra={}){if(busy)return;busy=true;draw();try{const snapshot=engine.save();snapshot.paused=wasPaused;apply(await api('POST',{action,revision:engine.s.marketRevision,state:snapshot,...extra}));offers=(await api('GET')).listings;connected=true;status.textContent='Jugador '+player+' · '+C.currency.format(engine.s.gramUnits)+' Gram · Comisión de venta '+C.marketFeePercent+'%';if(action==='publish')view='mine';toast(action==='buy'?'Equipo comprado y guardado':action==='cancel'?'Equipo recuperado':action==='publish'?'Oferta publicada':'Mercado actualizado');}catch(error){status.textContent=error.message;}finally{busy=false;draw();}}
function pieceCard(slot){const base=C.items.find(i=>i.id===slot.itemId),piece={...base,level:slot.level||1,rarity:slot.rarity||base.rarity},card=document.createElement('article');card.className='market-card';card.setAttribute('data-rarity',piece.rarity);const icon=document.createElement('div');icon.className='market-icon';bagIcon(icon,piece.icon,piece.rarity,piece.level);const title=document.createElement('h2');title.textContent=piece.name;const meta=document.createElement('small');meta.textContent=piece.rarity+' · Nv. '+piece.level+' · '+C.heroes.find(h=>h.id===piece.hero).className;const stats=document.createElement('p'),factor=(1+(piece.level-1)*.15)*C.rarities[piece.rarity];stats.textContent='⚔ '+Math.floor((piece.attack||0)*factor)+' · ♥ '+Math.floor((piece.hp||0)*factor)+' · ◈ '+Math.floor((piece.defense||0)*factor);card.append(icon,title,meta,stats);return card;}
function draw(){content.replaceChildren();for(const id of ['market-offers','market-sell','market-mine','market-refresh'])$(id).disabled=busy||(id!=='market-refresh'&&!connected);if(!connected){const grid=document.createElement('div');grid.className='market-grid';emptySlots(grid);content.append(grid);return;}if(view==='sell'){const hint=document.createElement('p');hint.textContent='Selecciona un precio en Gram. Desequipa el objeto para publicarlo. Puedes mantener hasta 20 ofertas activas. Comisión del 5% al vender (redondeada hacia arriba a 0.01 Gram).';content.append(hint);let count=0;engine.s.bag.forEach((slot,index)=>{const piece=engine.itemAt(index);if(!piece||piece.kind==='potion')return;count++;const card=pieceCard(slot),equipped=Object.values(engine.s.equipment).includes(index);const form=document.createElement('form'),label=document.createElement('label');label.textContent='Precio en Gram';const price=document.createElement('input');price.type='number';price.min='0.01';price.max='1000000';price.step='0.01';price.required=true;price.value='100';price.setAttribute('aria-label','Precio de '+piece.name+' en Gram');const submit=document.createElement('button');submit.className='primary';submit.type='submit';submit.textContent=equipped?'Desequipa para vender':'Publicar oferta';submit.disabled=busy||equipped;form.onsubmit=event=>{event.preventDefault();return act('publish',{index,price:Number(price.value)});};const quote=document.createElement('p');quote.className='market-fee';function updateQuote(){const units=C.currency.toUnits(price.value);if(!units){quote.textContent='Introduce un precio válido con hasta dos decimales.';return;}const fee=C.currency.fee(units,C.marketFeePercent);quote.textContent='Comisión '+C.marketFeePercent+'%: '+C.currency.format(fee)+' Gram · Recibirás '+C.currency.format(units-fee)+' Gram';}price.oninput=updateQuote;updateQuote();label.append(price);form.append(label,quote,submit);card.append(form);content.append(card);});if(!count)empty('No tienes equipo para vender.');return;}
const list=offers.filter(l=>view==='mine'?l.mine:!l.mine);const grid=document.createElement('div');grid.className='market-grid';for(const listing of list){const piece=C.items.find(i=>i.id===listing.item.itemId),slot=document.createElement('button');slot.className='market-sale-slot';slot.setAttribute('data-rarity',listing.item.rarity||piece.rarity);slot.setAttribute('aria-label',piece.name+' · '+(listing.currency==='Gram'?C.currency.format(listing.priceUnits)+' Gram':'Oferta antigua en Blez'));const icon=document.createElement('div');icon.className='market-slot-icon';bagIcon(icon,piece.icon,listing.item.rarity||piece.rarity,listing.item.level||1);const name=document.createElement('b');name.textContent=piece.name;const price=document.createElement('span');price.className='market-slot-price';price.textContent=listing.currency==='Gram'?C.currency.format(listing.priceUnits)+' Gram':'Antigua · Blez';const meta=document.createElement('small');meta.textContent='Nv. '+(listing.item.level||1)+' · '+(listing.item.rarity||piece.rarity);slot.append(icon,name,price,meta);slot.onclick=()=>listingDetail(listing);grid.append(slot);}emptySlots(grid);content.append(grid);if(!list.length)empty(view==='mine'?'No tienes ventas activas. El saldo Gram de tus ventas se refleja al actualizar.':'Todavía no hay ofertas de otros jugadores.');}
function listingDetail(listing){content.replaceChildren();const back=document.createElement('button');back.className='secondary';back.textContent='← Volver a los slots';back.onclick=draw;const card=pieceCard(listing.item),price=document.createElement('b');price.textContent=listing.currency==='Gram'?C.currency.format(listing.priceUnits)+' Gram':listing.price+' Blez · Retira y vuelve a publicar en Gram';const seller=document.createElement('p');seller.textContent='Vendedor '+listing.seller;if(listing.mine&&listing.currency==='Gram')seller.textContent+=' · Comisión '+C.currency.format(listing.feeUnits)+' Gram · Neto '+C.currency.format(listing.netUnits)+' Gram';const button=document.createElement('button');button.className='secondary';button.textContent=listing.mine?'Retirar y recuperar equipo':'Comprar · '+C.currency.format(listing.priceUnits||0)+' Gram';button.disabled=busy||(!listing.mine&&(listing.currency!=='Gram'||engine.s.gramUnits<listing.priceUnits||!engine.s.bag.some(s=>!s)));button.onclick=()=>act(listing.mine?'cancel':'buy',{id:listing.id});card.append(price,seller,button);content.append(back,card);}
function emptySlots(grid){while(grid.children.length<12){const slot=document.createElement('button');slot.className='market-sale-slot empty-market-slot';slot.disabled=true;slot.setAttribute('aria-label','Slot del mercado sin oferta');const icon=document.createElement('span');icon.textContent='◇';const label=document.createElement('small');label.textContent='Sin oferta';slot.append(icon,label);grid.append(slot);}}
function empty(text){const p=document.createElement('p');p.textContent=text;content.append(p);}
$('open-market').onclick=async()=>{if(dialog.open)return;wasPaused=engine.s.paused;engine.s.paused=true;connected=false;view='offers';status.textContent='Conectando con el mercado…';dialog.showModal();draw();await act('sync');if(dialog.open)refreshTimer=setInterval(async()=>{if(busy||view==='sell'||!dialog.open||!connected)return;try{offers=(await api('GET')).listings;draw();}catch{status.textContent='Conexión perdida. Pulsa actualizar para reintentar.';}},8000);};
function closeMarket(){clearInterval(refreshTimer);engine.s.paused=wasPaused;persist();render();}
$('close-market').onclick=()=>{if(busy)return;dialog.close();closeMarket();};dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();});dialog.addEventListener('close',closeMarket);
globalThis.syncGramWallet=async()=>{if(busy||dialog.open)throw new Error('Cierra el mercado para actualizar tus retiros.');busy=true;const paused=engine.s.paused;engine.s.paused=true;try{const snapshot=engine.save();snapshot.paused=paused;apply(await api('POST',{action:'sync',revision:engine.s.marketRevision,state:snapshot}));}finally{engine.s.paused=paused;busy=false;persist();render();}};
$('market-offers').onclick=()=>{view='offers';draw();};$('market-sell').onclick=()=>{view='sell';draw();};$('market-mine').onclick=()=>{view='mine';draw();};$('market-refresh').onclick=()=>act('sync');
})();
