/* Viewport and fullscreen integration; game works even when the Telegram SDK is unavailable. */
(function(root){'use strict';const doc=root.document,html=doc.documentElement,button=doc.getElementById('fullscreen'),sdk=doc.getElementById('telegram-sdk');let tg=null;
const call=(name,...args)=>{try{return tg?.[name]?.(...args);}catch{return undefined;}};
function viewport(){const height=tg?.viewportHeight||root.visualViewport?.height||root.innerHeight;if(Number.isFinite(height)&&height>0)html.style.setProperty('--game-height',Math.round(height)+'px');for(const edge of ['top','right','bottom','left']){const system=Number(tg?.safeAreaInset?.[edge])||0,content=Number(tg?.contentSafeAreaInset?.[edge])||0;html.style.setProperty('--mini-safe-'+edge,Math.max(0,system+content)+'px');}}
function state(){if(!button)return;const full=tg?tg.isFullscreen:!!(doc.fullscreenElement||doc.webkitFullscreenElement);button.textContent=full?'⊡':'⛶';button.setAttribute('aria-label',full?'Salir de pantalla completa':'Pantalla completa');button.title=full?'Salir de pantalla completa':'Pantalla completa';button.setAttribute('aria-pressed',String(full));button.hidden=tg?!tg.isVersionAtLeast?.('8.0'):!(html.requestFullscreen||html.webkitRequestFullscreen);viewport();}
async function fullscreen(){try{if(tg){call(tg.isFullscreen?'exitFullscreen':'requestFullscreen');}else if(doc.fullscreenElement||doc.webkitFullscreenElement){await (doc.exitFullscreen||doc.webkitExitFullscreen)?.call(doc);}else{await (html.requestFullscreen||html.webkitRequestFullscreen)?.call(html);}}catch{if(typeof root.toast==='function')root.toast('Tu navegador no permite pantalla completa. El juego sigue ajustado a tu pantalla.');}state();}
function telegram(){const app=root.Telegram?.WebApp;if(tg||!app||!(app.initData||(app.platform&&app.platform!=='unknown')))return;tg=app;html.classList.add('telegram-mode');call('ready');call('setHeaderColor','#171a23');call('setBackgroundColor','#171a23');if(app.isVersionAtLeast?.('7.10'))call('setBottomBarColor','#1d222d');call('expand');for(const event of ['viewportChanged','safeAreaChanged','contentSafeAreaChanged','fullscreenChanged','fullscreenFailed'])call('onEvent',event,state);if(app.isVersionAtLeast?.('8.0'))call('requestFullscreen');state();}
button?.addEventListener('click',fullscreen);root.addEventListener('resize',viewport);root.visualViewport?.addEventListener('resize',viewport);doc.addEventListener('fullscreenchange',state);doc.addEventListener('webkitfullscreenchange',state);sdk?.addEventListener('load',telegram);telegram();state();
})(globalThis);
