const test=require('node:test'),assert=require('node:assert/strict');const {Engine}=require('../js/engine.js');
function arrive(e){while(e.phase==='walk'||e.phase==='approach')e.tick();}
test('sin héroe no genera recompensas',()=>{const e=new Engine();for(let i=0;i<100;i++)e.tick();assert.equal(e.s.coins,0);assert.equal(e.s.kills,0);});
test('compra de prueba activa combate y mejora descuenta monedas',()=>{const e=new Engine();assert.equal(e.acquire('fake'),false);e.acquire('warrior');for(let i=0;i<100;i++)e.tick();assert.ok(e.s.kills>0);assert.ok(e.s.coins>=20);const before=e.s.coins,cost=e.cost,attack=e.attack;assert.ok(e.upgrade());assert.equal(e.s.coins,before-cost);assert.equal(e.attack,attack+4);});
test('jefe desbloquea solo siguiente zona y viaje respeta bloqueos',()=>{const e=new Engine();e.acquire('mage');e.s.weapon=100;while(e.s.kills<10)e.tick();assert.equal(e.s.zone,1);assert.equal(e.s.unlocked,1);assert.equal(e.s.wave,1);assert.equal(e.travel(2),false);assert.equal(e.travel(-1),false);assert.equal(e.travel(1),true);});
test('pausa impide generar monedas',()=>{const e=new Engine();e.acquire('ranger');e.s.paused=true;const before=e.save();for(let i=0;i<100;i++)e.tick();assert.equal(e.s.coins,before.coins);assert.equal(e.s.enemyHp,before.enemyHp);});
test('cofre offline tiene límite de 8h y no se duplica al reclamar',()=>{const e=new Engine();e.acquire('warrior');const save=e.save();save.lastSeen=Date.now()-86400000;const resumed=new Engine(save);assert.equal(resumed.s.pending,Math.floor(28800*resumed.offlineRate()));const amount=resumed.claim();assert.ok(amount>0);assert.equal(resumed.claim(),0);assert.equal(resumed.s.coins,amount);});
test('partida pausada o con fecha futura no acumula offline',()=>{const e=new Engine();e.acquire('mage');const s=e.save();s.paused=true;s.lastSeen=Date.now()-86400000;assert.equal(new Engine(s).s.pending,0);s.paused=false;s.lastSeen=Date.now()+86400000;assert.equal(new Engine(s).s.pending,0);});
test('recorrido automático llega al último stage y se detiene',()=>{const e=new Engine();e.acquire('warrior');e.s.weapon=1000;e.s.level=100;e.resetFight();for(let i=0;i<1000&&!e.s.completed;i++)e.tick();assert.equal(e.s.completed,true);assert.equal(e.s.unlocked,3);assert.equal(e.stage,40);assert.equal(e.s.kills,80);const coins=e.s.coins;for(let i=0;i<30;i++)assert.equal(e.tick().type,'idle');assert.equal(e.s.coins,coins);assert.equal(e.offlineRate(),0);const resumed=new Engine(e.save());assert.equal(resumed.s.completed,true);assert.ok(resumed.restart());assert.equal(resumed.stage,1);assert.equal(resumed.phase,'walk');assert.equal(resumed.s.coins,coins);});
test('Blez cobra el héroe económico y no cobra dos veces',()=>{const e=new Engine();assert.equal(e.buy('warrior'),false);assert.equal(e.hero,undefined);e.demoCredit();assert.equal(e.s.coins,5000);assert.ok(e.buy('warrior'));assert.equal(e.s.coins,0);assert.ok(e.buy('warrior'));assert.equal(e.s.coins,0);});
test('conversión propuesta Blez TON respeta cantidad y saldo',()=>{const e=new Engine();e.demoCredit();assert.equal(e.quoteWithdrawal(5000).ton,.5);assert.equal(e.quoteWithdrawal(10000).ton,1);assert.equal(e.quoteWithdrawal(5000).covered,true);assert.equal(e.quoteWithdrawal(10000).covered,false);assert.equal(e.quoteWithdrawal(-1),null);assert.equal(e.quoteWithdrawal(1.5),null);assert.equal(e.quoteWithdrawal(NaN),null);assert.equal(e.s.coins,5000);});

test('el enemigo responde en su turno y una muerte no permite contraataque',()=>{const e=new Engine();e.acquire('warrior');arrive(e);const hp=e.s.hp;const hit=e.tick();assert.equal(hit.type,'hit');assert.equal(e.s.hp,hp);assert.equal(e.tick().type,'enemyHit');assert.equal(e.s.hp,hp-e.enemyAttack);e.s.enemyHp=1;e.mobHps[0]=1;const before=e.s.hp;assert.equal(e.tick().type,'kill');assert.ok(e.s.hp>=before);assert.equal(e.phase,'walk');});
test('cada clase activa su habilidad al cuarto golpe',()=>{for(const id of ['warrior','ranger','mage']){const e=new Engine();e.acquire(id);arrive(e);e.s.enemyHp=10000;e.mobHps[0]=10000;for(let i=0;i<3;i++){assert.equal(e.tick().skill,false);e.tick();}const event=e.tick();assert.equal(event.skill,true);assert.equal(event.move,e.skillName);assert.ok(event.damage>e.attack);assert.equal(e.charge,0);}});
test('caída exige recuperación, sin recompensas, y pausa congela recuperación',()=>{const e=new Engine();e.acquire('warrior');arrive(e);e.tick();e.s.hp=1;const coins=e.s.coins;assert.equal(e.tick().type,'rest');assert.equal(e.s.hp,0);assert.equal(e.restTicks,3);e.s.paused=true;assert.equal(e.tick().type,'idle');assert.equal(e.restTicks,3);e.s.paused=false;for(let i=0;i<3;i++)assert.equal(e.tick().type,'recover');assert.equal(e.s.hp,e.maxHp);assert.equal(e.s.enemyHp,e.enemyMax);assert.equal(e.s.coins,coins);assert.equal(e.s.kills,0);assert.equal(e.phase,'walk');arrive(e);assert.equal(e.tick().type,'hit');});

test('guardar y volver conserva heridas y recuperación',()=>{const e=new Engine();e.acquire('mage');e.s.hp=12;assert.equal(new Engine(e.save()).s.hp,12);e.s.hp=0;const loaded=new Engine(e.save());assert.equal(loaded.s.hp,0);assert.equal(loaded.restTicks,3);});

test('caminar y aproximación no causan daño ni botín; pausa congela recorrido',()=>{const e=new Engine();e.acquire('ranger');const hp=e.s.hp,enemy=e.s.enemyHp;assert.equal(e.phase,'walk');assert.equal(e.tick().type,'walk');e.s.paused=true;const remaining=e.travelTicks;for(let i=0;i<4;i++)e.tick();assert.equal(e.travelTicks,remaining);e.s.paused=false;assert.equal(e.tick().type,'approach');assert.equal(e.tick().type,'approach');assert.equal(e.tick().type,'encounter');assert.equal(e.s.hp,hp);assert.equal(e.s.enemyHp,enemy);assert.equal(e.s.coins,0);assert.equal(e.tick().type,'hit');});
test('cada victoria inicia caminata antes del siguiente enemigo',()=>{const e=new Engine();e.acquire('mage');e.s.weapon=100;arrive(e);assert.equal(e.tick().type,'kill');assert.equal(e.stage,2);assert.equal(e.phase,'walk');const kills=e.s.kills;for(let i=0;i<4;i++)e.tick();assert.equal(e.s.kills,kills);assert.equal(e.phase,'hero');});

test('dos últimas áreas traen tres mobs y el jefe tiene dos escoltas',()=>{const e=new Engine();e.acquire('warrior');for(let zone=0;zone<4;zone++){e.s.zone=zone;e.s.wave=1;e.resetFight();assert.equal(e.mobCount,zone<2?1:3);assert.equal(e.enemyMax,e.zone.hp*e.mobCount);assert.equal(e.enemyAttack,e.zone.damage*e.mobCount);}e.s.wave=10;e.resetFight();assert.equal(e.mobHps.length,3);assert.equal(e.mobHps[0],e.mobHps[1]*4);assert.equal(e.enemyAttack,e.zone.damage*4);});
test('un stage de grupo termina solo tras vencer a sus tres mobs',()=>{const e=new Engine();e.acquire('warrior');e.s.zone=2;e.s.weapon=1000;e.resetFight();arrive(e);const reward=e.reward;assert.equal(e.tick().type,'hit');assert.equal(e.aliveMobs,2);assert.equal(e.s.wave,1);assert.equal(e.s.coins,0);assert.equal(e.tick().damage,e.zone.damage*2);assert.equal(e.tick().type,'hit');assert.equal(e.aliveMobs,1);assert.equal(e.tick().damage,e.zone.damage);assert.equal(e.tick().type,'kill');assert.equal(e.s.wave,2);assert.equal(e.s.kills,3);assert.equal(e.s.coins,reward);assert.equal(e.phase,'walk');});

test('recuperación reinicia el grupo completo sin conceder botín parcial',()=>{const e=new Engine();e.acquire('mage');e.s.zone=2;e.s.weapon=1000;e.resetFight();arrive(e);e.tick();assert.equal(e.aliveMobs,2);e.s.hp=1;assert.equal(e.tick().type,'rest');for(let i=0;i<3;i++)e.tick();assert.equal(e.aliveMobs,3);assert.equal(e.s.enemyHp,e.enemyMax);assert.equal(e.s.coins,0);assert.equal(e.s.kills,0);assert.equal(e.s.wave,1);});

test('morir en cualquier área vuelve a stage 1 y conserva progreso adquirido',()=>{for(let zone=0;zone<4;zone++){const e=new Engine();e.acquire('warrior');e.s.zone=zone;e.s.unlocked=3;e.s.wave=10;e.s.coins=123;e.s.level=5;e.s.weapon=2;e.s.xp=7;e.resetFight();arrive(e);e.tick();e.s.hp=1;const event=e.tick();assert.equal(event.type,'rest');assert.equal(event.fromStage,10);assert.equal(e.s.zone,zone);assert.equal(e.s.wave,1);assert.equal(e.s.coins,123);assert.equal(e.s.level,5);assert.equal(e.s.weapon,2);assert.equal(e.s.xp,7);assert.equal(e.s.unlocked,3);assert.equal(e.s.recovering,true);assert.equal(e.s.hp,0);const loaded=new Engine(e.save());assert.equal(loaded.s.zone,zone);assert.equal(loaded.s.wave,1);assert.equal(loaded.phase,'recovery');e.tick();const mid=new Engine(e.save());assert.equal(mid.s.recovering,true);assert.equal(mid.phase,'recovery');for(let i=0;i<2;i++)e.tick();assert.equal(e.s.hp,e.maxHp);assert.equal(e.phase,'walk');assert.equal(e.s.recovering,false);assert.equal(e.tick().type,'walk');}});
