const test=require('node:test'),assert=require('node:assert/strict');const {Engine}=require('../js/engine.js');
test('sin héroe no genera recompensas',()=>{const e=new Engine();for(let i=0;i<100;i++)e.tick();assert.equal(e.s.coins,0);assert.equal(e.s.kills,0);});
test('compra de prueba activa combate y mejora descuenta monedas',()=>{const e=new Engine();assert.equal(e.acquire('fake'),false);e.acquire('warrior');for(let i=0;i<100;i++)e.tick();assert.ok(e.s.kills>0);assert.ok(e.s.coins>=20);const before=e.s.coins,cost=e.cost,attack=e.attack;assert.ok(e.upgrade());assert.equal(e.s.coins,before-cost);assert.equal(e.attack,attack+4);});
test('jefe desbloquea solo siguiente zona y viaje respeta bloqueos',()=>{const e=new Engine();e.acquire('mage');e.s.weapon=100;for(let i=0;i<10;i++)e.tick();assert.equal(e.s.unlocked,1);assert.equal(e.s.wave,1);assert.equal(e.travel(2),false);assert.equal(e.travel(-1),false);assert.equal(e.travel(1),true);});
test('pausa impide generar monedas',()=>{const e=new Engine();e.acquire('ranger');e.s.paused=true;const before=e.save();for(let i=0;i<100;i++)e.tick();assert.equal(e.s.coins,before.coins);assert.equal(e.s.enemyHp,before.enemyHp);});
test('cofre offline tiene límite de 8h y no se duplica al reclamar',()=>{const e=new Engine();e.acquire('warrior');const save=e.save();save.lastSeen=Date.now()-86400000;const resumed=new Engine(save);assert.equal(resumed.s.pending,Math.floor(28800*resumed.offlineRate()));const amount=resumed.claim();assert.ok(amount>0);assert.equal(resumed.claim(),0);assert.equal(resumed.s.coins,amount);});
test('partida pausada o con fecha futura no acumula offline',()=>{const e=new Engine();e.acquire('mage');const s=e.save();s.paused=true;s.lastSeen=Date.now()-86400000;assert.equal(new Engine(s).s.pending,0);s.paused=false;s.lastSeen=Date.now()+86400000;assert.equal(new Engine(s).s.pending,0);});
test('progresión completa vence todos los jefes',()=>{const e=new Engine();e.acquire('warrior');e.s.weapon=100;for(let zone=0;zone<4;zone++){assert.ok(e.travel(zone));for(let i=0;i<150&&e.s.zone===zone;i++){e.tick();if(e.s.wave===1&&e.s.kills>zone*10)break;}assert.equal(e.s.unlocked,Math.min(3,zone+1));}assert.equal(e.s.kills,40);});
test('Blez cobra el héroe económico y no cobra dos veces',()=>{const e=new Engine();assert.equal(e.buy('warrior'),false);assert.equal(e.hero,undefined);e.demoCredit();assert.equal(e.s.coins,5000);assert.ok(e.buy('warrior'));assert.equal(e.s.coins,0);assert.ok(e.buy('warrior'));assert.equal(e.s.coins,0);});
test('conversión propuesta Blez TON respeta cantidad y saldo',()=>{const e=new Engine();e.demoCredit();assert.equal(e.quoteWithdrawal(5000).ton,.5);assert.equal(e.quoteWithdrawal(10000).ton,1);assert.equal(e.quoteWithdrawal(5000).covered,true);assert.equal(e.quoteWithdrawal(10000).covered,false);assert.equal(e.quoteWithdrawal(-1),null);assert.equal(e.quoteWithdrawal(1.5),null);assert.equal(e.quoteWithdrawal(NaN),null);assert.equal(e.s.coins,5000);});

test('el enemigo responde en su turno y una muerte no permite contraataque',()=>{const e=new Engine();e.acquire('warrior');const hp=e.s.hp;const hit=e.tick();assert.equal(hit.type,'hit');assert.equal(e.s.hp,hp);assert.equal(e.tick().type,'enemyHit');assert.equal(e.s.hp,hp-e.enemyAttack);e.s.enemyHp=1;const before=e.s.hp;assert.equal(e.tick().type,'kill');assert.ok(e.s.hp>=before);assert.equal(e.phase,'hero');});
test('cada clase activa su habilidad al cuarto golpe',()=>{for(const id of ['warrior','ranger','mage']){const e=new Engine();e.acquire(id);e.s.enemyHp=10000;for(let i=0;i<3;i++){assert.equal(e.tick().skill,false);e.tick();}const event=e.tick();assert.equal(event.skill,true);assert.equal(event.move,e.skillName);assert.ok(event.damage>e.attack);assert.equal(e.charge,0);}});
test('caída exige recuperación, sin recompensas, y pausa congela recuperación',()=>{const e=new Engine();e.acquire('warrior');e.tick();e.s.hp=1;const coins=e.s.coins;assert.equal(e.tick().type,'rest');assert.equal(e.s.hp,0);assert.equal(e.restTicks,3);e.s.paused=true;assert.equal(e.tick().type,'idle');assert.equal(e.restTicks,3);e.s.paused=false;for(let i=0;i<3;i++)assert.equal(e.tick().type,'recover');assert.equal(e.s.hp,e.maxHp);assert.equal(e.s.enemyHp,e.enemyMax);assert.equal(e.s.coins,coins);assert.equal(e.s.kills,0);assert.equal(e.tick().type,'hit');});

test('guardar y volver conserva heridas y recuperación',()=>{const e=new Engine();e.acquire('mage');e.s.hp=12;assert.equal(new Engine(e.save()).s.hp,12);e.s.hp=0;const loaded=new Engine(e.save());assert.equal(loaded.s.hp,0);assert.equal(loaded.restTicks,3);});
