'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{tmpdir}=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto'),{once}=require('node:events');
const {createServer,saleFee}=require('../server/market'),{Engine}=require('../js/engine');
async function fixture(balances=[0,100000,100000]){
 const dir=fs.mkdtempSync(path.join(tmpdir(),'etherial-market-')),dataFile=path.join(dir,'market.json'),players=balances.map(gramUnits=>{const e=new Engine();e.acquire('warrior');e.s.coins=1000;for(const slot of e.s.bag){if(slot&&slot.itemId!=='health-potion')slot.marketable=true;}return {token:randomUUID(),e,revision:0,gramUnits};});const accounts=Object.fromEntries(players.map(p=>[p.token,{id:randomUUID(),revision:0,state:null,credits:0,gramUnits:p.gramUnits,gramSalesUnits:0}]));fs.writeFileSync(dataFile,JSON.stringify({accounts,listings:[]}));let server,base;
 async function start(){server=createServer({dataFile});server.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port;}await start();
 return {players,dataFile,async post(p,action,extra={}){const res=await fetch(base+'/api/market',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+p.token},body:JSON.stringify({action,revision:p.revision,state:p.e.save(),...extra})});const data=await res.json();if(res.ok){p.revision=data.revision;p.e=new Engine(data.state);}return {status:res.status,data};},async offers(p){return(await(await fetch(base+'/api/market',{headers:{Authorization:'Bearer '+p.token}})).json()).listings;},async restart(){await new Promise(r=>server.close(r));await start();},async close(){await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});},async privateFile(){return(await fetch(base+'/.data/market.json')).status;}};
}
test('mercado Gram: venta única concurrente, comisión 5%, saldo neto del vendedor y persistencia',async()=>{
 const f=await fixture(),[seller,buyer,other]=f.players;seller.e.s.bag[0].rarity='Épico';seller.e.s.bag[0].level=20;
 try{assert.equal((await f.post(seller,'publish',{index:0,price:250})).status,200);assert.equal(seller.e.s.bag[0],null);const listing=(await f.offers(buyer))[0];assert.equal(listing.currency,'Gram');assert.equal(listing.priceUnits,25000);assert.equal(listing.feeUnits,1250);assert.equal(listing.netUnits,23750);assert.equal(listing.mine,false);assert.equal(listing.token,undefined);
 const results=await Promise.all([f.post(buyer,'buy',{id:listing.id}),f.post(other,'buy',{id:listing.id})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const winner=results[0].status===200?buyer:other;assert.equal(winner.e.s.gramUnits,75000);assert.equal(winner.e.s.coins,1000);assert.ok(winner.e.s.bag.some(s=>s?.rarity==='Épico'&&s.level===20));assert.equal((await f.offers(seller)).length,0);
 await f.post(seller,'sync');assert.equal(seller.e.s.gramUnits,23750);assert.equal(seller.e.s.gramSalesUnits,23750);assert.equal(seller.e.s.coins,1000);await f.post(seller,'sync');assert.equal(seller.e.s.gramUnits,23750);
 await f.post(seller,'publish',{index:1,price:90});const own=(await f.offers(seller))[0];assert.equal(own.mine,true);assert.equal((await f.post(seller,'buy',{id:own.id})).status,400);assert.equal((await f.post(buyer,'cancel',{id:own.id})).status,403);await f.restart();assert.equal((await f.offers(seller)).length,1);assert.equal((await f.post(seller,'cancel',{id:own.id})).status,200);assert.equal((await f.offers(seller)).length,0);assert.equal(seller.e.s.gramUnits,23750);assert.equal(JSON.parse(fs.readFileSync(f.dataFile)).gramFeesCollectedUnits,1250);assert.ok(seller.e.s.bag.some(s=>s?.itemId==='ash-bow'));
 const revision=seller.revision;seller.revision=0;const stale=await f.post(seller,'sync');assert.equal(stale.status,409);assert.ok(stale.data.state);seller.revision=revision;
 }finally{await f.close();}
});
test('mercado valida clase de objeto, precio decimal, saldo Gram del servidor y espacio sin cobrar',async()=>{
 const f=await fixture([0,0,100000]),[seller,poor,buyer]=f.players;try{seller.e.equip(0);assert.equal((await f.post(seller,'publish',{index:0,price:1})).status,400);seller.e.unequip(0);assert.equal((await f.post(seller,'publish',{index:8,price:1})).status,400);for(const price of [-1,.001,1.005,1000001])assert.equal((await f.post(seller,'publish',{index:0,price})).status,400);assert.equal((await f.post(seller,'publish',{index:0,price:50.25})).status,200);const listing=(await f.offers(buyer))[0];assert.equal(listing.priceUnits,5025);assert.equal(listing.feeUnits,252);
 poor.e.s.gramUnits=10000000;assert.equal((await f.post(poor,'buy',{id:listing.id})).status,400);buyer.e.s.bag=buyer.e.s.bag.map(()=>({itemId:'dawn-sword',quantity:1}));assert.equal((await f.post(buyer,'buy',{id:listing.id})).status,400);assert.equal((await f.offers(seller)).length,1);assert.equal(await f.privateFile(),404);const ledger=JSON.parse(fs.readFileSync(f.dataFile));assert.equal(ledger.accounts[buyer.token].gramUnits,100000);assert.equal(ledger.gramFeesCollectedUnits,undefined);
 }finally{await f.close();}
});
test('comisión Gram del 5% redondea a centésimas y conserva bruto = neto + comisión',()=>{for(const [units,fee] of [[1,1],[20,1],[21,2],[100,5],[250,13],[10000,500],[100000000,5000000]]){assert.equal(saleFee(units),fee);assert.equal(units-fee+saleFee(units),units);}});
test('ofertas Blez antiguas se recuperan sin convertir precio ni saldo a Gram',async()=>{const f=await fixture(),[seller,buyer]=f.players;try{await f.post(seller,'publish',{index:0,price:100});const ledger=JSON.parse(fs.readFileSync(f.dataFile));const listing=ledger.listings[0];delete listing.currency;delete listing.priceUnits;delete listing.feeUnits;delete listing.netUnits;listing.price=100;ledger.accounts[seller.token].credits=95;fs.writeFileSync(f.dataFile,JSON.stringify(ledger));await f.restart();assert.equal((await f.post(buyer,'buy',{id:listing.id})).status,400);assert.equal((await f.post(seller,'cancel',{id:listing.id})).status,200);assert.equal(seller.e.s.gramUnits,0);assert.equal(seller.e.s.coins,1095);assert.ok(seller.e.s.bag.some(s=>s?.itemId==='dawn-sword'));}finally{await f.close();}});

test('solo equipo comerciable y mínimos por rareza se validan en el servidor',async()=>{const f=await fixture(),[seller]=f.players;try{seller.e.s.bag[0].marketable=false;assert.equal((await f.post(seller,'publish',{index:0,price:100})).status,400);seller.e.s.bag[0].marketable=true;for(const [rarity,min] of [['Común',.10],['Poco común',.50],['Raro',.80],['Épico',1],['Legendario',3]]){seller.e.s.bag[0].rarity=rarity;assert.equal((await f.post(seller,'publish',{index:0,price:min-.01})).status,400);assert.equal((await f.post(seller,'publish',{index:0,price:min})).status,200);const listing=(await f.offers(seller))[0];assert.equal(listing.item.marketable,true);assert.equal((await f.post(seller,'cancel',{id:listing.id})).status,200);assert.equal(seller.e.itemAt(0).marketable,true);}}finally{await f.close();}});
test('mercado sigue añadiendo ofertas después de veinte publicaciones',async()=>{const f=await fixture(),[seller]=f.players;try{for(let i=0;i<25;i++){if(!seller.e.s.bag[0])seller.e.addItem('dawn-sword',1,{marketable:true});assert.equal((await f.post(seller,'publish',{index:0,price:1})).status,200);}assert.equal((await f.offers(seller)).length,25);}finally{await f.close();}});
