'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{tmpdir}=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto'),{once}=require('node:events');
const {createServer,saleFee}=require('../server/market'),{Engine}=require('../js/engine');
async function fixture(balances=[0,100000,100000]){
 const dir=fs.mkdtempSync(path.join(tmpdir(),'etherial-market-')),dataFile=path.join(dir,'market.json'),players=balances.map(gramUnits=>{const e=new Engine();e.acquire('warrior');e.s.coins=1000;for(const slot of e.s.bag){if(slot&&slot.itemId!=='health-potion')slot.marketable=true;}return {token:randomUUID(),e,revision:0,gramUnits};});const accounts=Object.fromEntries(players.map(p=>[p.token,{id:randomUUID(),revision:0,state:null,credits:0,gramUnits:p.gramUnits,gramSalesUnits:0}]));fs.writeFileSync(dataFile,JSON.stringify({accounts,listings:[]}));let server,base;
 async function start(){server=createServer({dataFile,seedCatalog:false});server.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port;}await start();
 return {players,dataFile,async post(p,action,extra={}){const res=await fetch(base+'/api/market',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+p.token},body:JSON.stringify({action,revision:p.revision,state:p.e.save(),...extra})});const data=await res.json();if(res.ok){p.revision=data.revision;p.e=new Engine(data.state);}return {status:res.status,data};},async offers(p){return(await(await fetch(base+'/api/market',{headers:{Authorization:'Bearer '+p.token}})).json()).listings;},async history(p){return(await(await fetch(base+'/api/market',{headers:{Authorization:'Bearer '+p.token}})).json()).sales;},async restart(){await new Promise(r=>server.close(r));await start();},async close(){await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});},async privateFile(){return(await fetch(base+'/.data/market.json')).status;}};
}
test('mercado Gram: venta única concurrente, comisión 5%, saldo neto del vendedor y persistencia',async()=>{
 const f=await fixture(),[seller,buyer,other]=f.players;seller.e.s.bag[0].rarity='Épico';seller.e.s.bag[0].level=20;
 try{assert.equal((await f.post(seller,'publish',{index:0,price:250})).status,200);assert.equal(seller.e.s.bag[0],null);const listing=(await f.offers(buyer))[0];assert.equal(listing.currency,'Gram');assert.equal(listing.priceUnits,25000);assert.equal(listing.feeUnits,1250);assert.equal(listing.netUnits,23750);assert.equal(listing.mine,false);assert.equal(listing.token,undefined);
 const results=await Promise.all([f.post(buyer,'buy',{id:listing.id}),f.post(other,'buy',{id:listing.id})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const winner=results[0].status===200?buyer:other;assert.equal(winner.e.s.gramUnits,75000);assert.equal(winner.e.s.coins,1000);assert.ok(winner.e.s.bag.some(s=>s?.rarity==='Épico'&&s.level===20));assert.equal((await f.offers(seller)).length,0);
 await f.post(seller,'sync');assert.equal(seller.e.s.gramUnits,23750);assert.equal(seller.e.s.gramSalesUnits,23750);assert.equal(seller.e.s.coins,1000);await f.post(seller,'sync');assert.equal(seller.e.s.gramUnits,23750);
 await f.post(seller,'publish',{index:1,price:90});const own=(await f.offers(seller))[0];assert.equal(own.mine,true);assert.equal((await f.post(seller,'buy',{id:own.id})).status,400);assert.equal((await f.post(buyer,'cancel',{id:own.id})).status,403);await f.restart();assert.equal((await f.offers(seller)).length,1);assert.equal((await f.post(seller,'cancel',{id:own.id})).status,200);assert.equal((await f.offers(seller)).length,0);assert.equal(seller.e.s.gramUnits,23750);assert.equal(JSON.parse(fs.readFileSync(f.dataFile)).gramFeesCollectedUnits,1250);assert.ok(seller.e.s.bag.some(s=>s?.itemId==='ash-bow'));
 const revision=seller.revision;seller.revision=0;const stale=await f.post(seller,'sync');assert.equal(stale.status,409);assert.ok(stale.data.state);seller.revision=revision;
 }finally{await f.close();}
});
test('mercado valida clase de objeto, precio decimal, saldo Gram del servidor y espacio sin cobrar',async()=>{
 const f=await fixture([0,0,100000]),[seller,poor,buyer]=f.players;try{seller.e.equip(0);assert.equal((await f.post(seller,'publish',{index:0,price:1})).status,400);seller.e.unequip(0);assert.equal((await f.post(seller,'publish',{index:8,price:1})).status,400);for(const price of [-1,.001,1.005,1000001])assert.equal((await f.post(seller,'publish',{index:0,price})).status,400);assert.equal((await f.post(seller,'publish',{index:0,price:50.25})).status,200);const listing=(await f.offers(buyer))[0];assert.equal(listing.priceUnits,5025);assert.equal(listing.feeUnits,252);
 poor.e.s.gramUnits=10000000;assert.equal((await f.post(poor,'buy',{id:listing.id})).status,400);buyer.e.s.bag=buyer.e.s.bag.map(()=>({itemId:'dawn-sword',quantity:1}));assert.equal((await f.post(buyer,'buy',{id:listing.id})).status,400);assert.equal((await f.offers(seller)).length,1);assert.equal(await f.privateFile(),404);const ledger=JSON.parse(fs.readFileSync(f.dataFile));assert.equal(ledger.accounts[buyer.token].gramUnits,100000);assert.equal(ledger.gramFeesCollectedUnits,undefined);
 }finally{await f.close();}
});
test('comisión Gram del 5% redondea a centésimas y conserva bruto = neto + comisión',()=>{for(const [units,fee] of [[1,1],[20,1],[21,2],[100,5],[250,13],[10000,500],[100000000,5000000]]){assert.equal(saleFee(units),fee);assert.equal(units-fee+saleFee(units),units);}});
test('ofertas Blez antiguas se recuperan sin convertir precio ni saldo a Gram',async()=>{const f=await fixture(),[seller,buyer]=f.players;try{await f.post(seller,'publish',{index:0,price:100});const ledger=JSON.parse(fs.readFileSync(f.dataFile));const listing=ledger.listings[0];delete listing.currency;delete listing.priceUnits;delete listing.feeUnits;delete listing.netUnits;listing.price=100;ledger.accounts[seller.token].credits=95;fs.writeFileSync(f.dataFile,JSON.stringify(ledger));await f.restart();assert.equal((await f.post(buyer,'buy',{id:listing.id})).status,400);assert.equal((await f.post(seller,'cancel',{id:listing.id})).status,200);assert.equal(seller.e.s.gramUnits,0);assert.equal(seller.e.s.coins,1095);assert.ok(seller.e.s.bag.some(s=>s?.itemId==='dawn-sword'));}finally{await f.close();}});

test('solo equipo comerciable y mínimos por rareza se validan en el servidor',async()=>{const f=await fixture(),[seller]=f.players;try{seller.e.s.bag[0].marketable=false;assert.equal((await f.post(seller,'publish',{index:0,price:100})).status,400);seller.e.s.bag[0].marketable=true;for(const [rarity,min] of [['Común',.10],['Poco común',.50],['Raro',.80],['Épico',1],['Legendario',3]]){seller.e.s.bag[0].rarity=rarity;assert.equal((await f.post(seller,'publish',{index:0,price:min-.01})).status,400);assert.equal((await f.post(seller,'publish',{index:0,price:min})).status,200);const listing=(await f.offers(seller))[0];assert.equal(listing.item.marketable,true);assert.equal((await f.post(seller,'cancel',{id:listing.id})).status,200);assert.equal(seller.e.itemAt(0).marketable,true);}}finally{await f.close();}});
test('mercado sigue añadiendo ofertas después de veinte publicaciones',async()=>{const f=await fixture(),[seller]=f.players;try{for(let i=0;i<25;i++){if(!seller.e.s.bag[0])seller.e.addItem('dawn-sword',1,{marketable:true});assert.equal((await f.post(seller,'publish',{index:0,price:1})).status,200);}assert.equal((await f.offers(seller)).length,25);}finally{await f.close();}});

test('Mis ventas solo muestra ventas completadas del vendedor con hora persistente y neto',async()=>{const f=await fixture(),[seller,buyer,other]=f.players;try{assert.equal((await f.history(seller)).length,0);await f.post(seller,'publish',{index:0,price:100});const listing=(await f.offers(seller))[0];const before=Date.now();await f.post(buyer,'buy',{id:listing.id});const after=Date.now();const history=await f.history(seller);assert.equal(history.length,1);assert.equal(history[0].id,listing.id);assert.ok(history[0].soldAt>=before&&history[0].soldAt<=after);assert.equal(history[0].priceUnits,10000);assert.equal(history[0].feeUnits,500);assert.equal(history[0].netUnits,9500);assert.equal(history[0].token,undefined);assert.deepEqual(await f.history(buyer),[]);assert.deepEqual(await f.history(other),[]);await f.post(seller,'publish',{index:1,price:1});const active=(await f.offers(seller))[0];await f.post(seller,'cancel',{id:active.id});assert.equal((await f.history(seller)).length,1);await f.restart();assert.equal((await f.history(seller))[0].soldAt,history[0].soldAt);}finally{await f.close();}});
test('catálogo publica 135 piezas: nueve slots por clase y rareza con mínimos Gram',()=>{const C=require('../js/config');assert.equal(C.marketCatalog.length,135);assert.equal(new Set(C.marketCatalog.map(l=>l.id)).size,135);for(const hero of C.heroes){for(const rarity of Object.keys(C.rarities)){const set=C.marketCatalog.filter(l=>C.items.find(i=>i.id===l.item.itemId).hero===hero.id&&l.item.rarity===rarity);assert.equal(set.length,9);assert.deepEqual(new Set(set.map(l=>C.items.find(i=>i.id===l.item.itemId).kind)),new Set(C.equipmentSlots));for(const listing of set){assert.equal(listing.priceUnits,C.marketMinimums[rarity]);assert.equal(listing.item.marketable,true);assert.equal(listing.currency,'Gram');}}}});
test('servidor publica catálogo una sola vez y una compra conserva nivel, rareza y marca',async()=>{const dir=fs.mkdtempSync(path.join(tmpdir(),'etherial-catalog-')),dataFile=path.join(dir,'db.json'),token=randomUUID();fs.writeFileSync(dataFile,JSON.stringify({accounts:{[token]:{id:randomUUID(),revision:0,state:null,credits:0,gramUnits:1000,gramSalesUnits:0}},listings:[]}));let server,base;async function start(){server=createServer({dataFile});server.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port;}await start();try{const listings=(await(await fetch(base+'/api/market')).json()).listings;assert.equal(listings.length,135);const listing=listings.find(l=>l.item.itemId==='spell-book'&&l.item.rarity==='Legendario');assert.equal(listing.priceUnits,300);const e=new Engine();e.acquire('mage');const request={method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({action:'buy',revision:0,state:e.save(),id:listing.id})};const response=await fetch(base+'/api/market',request);assert.equal(response.status,200);const result=await response.json(),bought=result.state.bag.find(s=>s?.itemId==='spell-book'&&s.rarity==='Legendario');assert.equal(bought.marketable,true);assert.equal(bought.level,1);assert.equal(result.state.gramUnits,700);const ledger=JSON.parse(fs.readFileSync(dataFile));assert.equal(ledger.accounts['system-catalog'].gramUnits,285);await new Promise(r=>server.close(r));await start();const after=(await(await fetch(base+'/api/market')).json()).listings;assert.equal(after.length,135);assert.equal(after.some(l=>l.id===listing.id&&l.unlimited),true);}finally{await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}});
test('stock permanente vende la misma oferta a dos compradores y acredita al propietario',async()=>{const dir=fs.mkdtempSync(path.join(tmpdir(),'etherial-unlimited-')),dataFile=path.join(dir,'db.json'),owner=randomUUID(),tokens=[randomUUID(),randomUUID()],accounts=Object.fromEntries(tokens.map(token=>[token,{id:randomUUID(),revision:0,state:null,credits:0,gramUnits:1000,gramSalesUnits:0}]));fs.writeFileSync(dataFile,JSON.stringify({accounts,listings:[]}));let server,base;async function start(){server=createServer({dataFile,ownerToken:owner});server.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port;}await start();async function post(token,e,action,extra={},revision=0){const response=await fetch(base+'/api/market',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({state:e.save(),revision,action,...extra})});return {status:response.status,data:await response.json()};}try{const initial=(await(await fetch(base+'/api/market')).json()).listings,listing=initial.find(l=>l.item.itemId==='dawn-sword'&&l.item.rarity==='Legendario');const engines=tokens.map(()=>{const e=new Engine();e.acquire('warrior');return e;});const results=await Promise.all(tokens.map((token,i)=>post(token,engines[i],'buy',{id:listing.id})));assert.deepEqual(results.map(r=>r.status),[200,200]);for(const result of results){assert.equal(result.data.state.gramUnits,700);assert.ok(result.data.state.bag.some(s=>s?.itemId==='dawn-sword'&&s.rarity==='Legendario'&&s.marketable));}const ledger=JSON.parse(fs.readFileSync(dataFile));assert.equal(ledger.accounts[owner].gramUnits,570);assert.equal(ledger.catalogSales.length,2);assert.equal(new Set(ledger.catalogSales.map(s=>s.id)).size,2);assert.deepEqual(ledger.ownerEarnings,{grossUnits:600,netUnits:570,feeUnits:30,salesCount:2});const history=(await(await fetch(base+'/api/market',{headers:{Authorization:'Bearer '+owner}})).json()).sales;assert.equal(history.length,2);assert.ok(history.every(s=>s.listingId===listing.id&&s.soldAt));const own=new Engine();own.acquire('warrior');const sync=await post(owner,own,'sync');assert.equal(sync.data.state.gramUnits,570);const denied=await post(owner,new Engine(sync.data.state),'buy',{id:listing.id},sync.data.revision);assert.equal(denied.status,400);await new Promise(r=>server.close(r));await start();assert.equal((await(await fetch(base+'/api/market')).json()).listings.length,135);assert.equal(JSON.parse(fs.readFileSync(dataFile)).ownerEarnings.salesCount,2);}finally{await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}});
